services:
  app-mysql:
    container_name: app-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hyperspectral
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3317:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
  app-back:
    container_name: app-back
    image: javaimage:latest  # 指定本地镜像
    volumes:
      - ./hyperspectral/:/app/
    ports:
      - "8081:8081"
  ggp_front:
    container_name: ggp_front
    image: nginx:latest
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "7586:7586"
  app-comcat:
    container_name: app-comcat
    image: tomcat:9.0
    volumes:
      - ./tomcat/webapps/:/usr/local/tomcat/webapps/
    ports:
      - "8082:8080"
  app-arithmetic:
    container_name: app-arithmetic
    image: my_new_image:latest  # 指定本地镜像
    ports:
      - "8091:8091"
      - "5001:5001"
